
GET https://sugaiapi.azurewebsites.net/api/todoitems
###
POST https://sugaiapi.azurewebsites.net/api/todoitems
Content-Type: application/json

{
  "name": "Web Api ready",
  "isComplete": true
}

